/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

function MyComponent(props) {
  return (
    <div className="bg-black flex flex-col">
      <div className="self-stretch flex w-full items-stretch justify-between gap-5 max-md:max-w-full max-md:flex-wrap">
        <img
          loading="lazy"
          srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/4f37cffd-a4f3-4baf-9a6b-c60baccbd71a?apiKey=f40b658cd7ce4263a246966552f667ce&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/4f37cffd-a4f3-4baf-9a6b-c60baccbd71a?apiKey=f40b658cd7ce4263a246966552f667ce&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/4f37cffd-a4f3-4baf-9a6b-c60baccbd71a?apiKey=f40b658cd7ce4263a246966552f667ce&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/4f37cffd-a4f3-4baf-9a6b-c60baccbd71a?apiKey=f40b658cd7ce4263a246966552f667ce&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/4f37cffd-a4f3-4baf-9a6b-c60baccbd71a?apiKey=f40b658cd7ce4263a246966552f667ce&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/4f37cffd-a4f3-4baf-9a6b-c60baccbd71a?apiKey=f40b658cd7ce4263a246966552f667ce&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/4f37cffd-a4f3-4baf-9a6b-c60baccbd71a?apiKey=f40b658cd7ce4263a246966552f667ce&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/4f37cffd-a4f3-4baf-9a6b-c60baccbd71a?apiKey=f40b658cd7ce4263a246966552f667ce&"
          className="aspect-[1.16] object-contain object-center w-full overflow-hidden grow basis-[0%] max-md:max-w-full"
        />
        <div className="self-center flex grow basis-[0%] flex-col items-stretch my-auto px-5 max-md:max-w-full">
          <img
            loading="lazy"
            srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/8a266eb6-3f28-4aa6-8278-0f309bb42957?apiKey=f40b658cd7ce4263a246966552f667ce&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/8a266eb6-3f28-4aa6-8278-0f309bb42957?apiKey=f40b658cd7ce4263a246966552f667ce&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/8a266eb6-3f28-4aa6-8278-0f309bb42957?apiKey=f40b658cd7ce4263a246966552f667ce&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/8a266eb6-3f28-4aa6-8278-0f309bb42957?apiKey=f40b658cd7ce4263a246966552f667ce&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/8a266eb6-3f28-4aa6-8278-0f309bb42957?apiKey=f40b658cd7ce4263a246966552f667ce&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/8a266eb6-3f28-4aa6-8278-0f309bb42957?apiKey=f40b658cd7ce4263a246966552f667ce&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/8a266eb6-3f28-4aa6-8278-0f309bb42957?apiKey=f40b658cd7ce4263a246966552f667ce&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/8a266eb6-3f28-4aa6-8278-0f309bb42957?apiKey=f40b658cd7ce4263a246966552f667ce&"
            className="aspect-[1.8] object-contain object-center w-full overflow-hidden self-center max-md:max-w-full"
          />
          <div className="text-white text-3xl font-extrabold leading-7 whitespace-nowrap items-center -mr-5 mt-2.5 pt-5 pb-7 px-5 max-md:max-w-full">
            COMPRAR AGORA
          </div>
          <div className="text-neutral-500 text-center text-base leading-4 mt-5">
            Um produto premiun produzido <br />
            por Casaec.com.br
          </div>
        </div>
      </div>
      <div className="bg-emerald-800 self-stretch flex min-h-[4px] w-full flex-col max-md:max-w-full" />
      <div className="flex-col overflow-hidden self-stretch relative flex min-h-[827px] w-full items-center mt-3.5 px-5 py-12 max-md:max-w-full">
        <img
          loading="lazy"
          srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/3c52da02-eb18-4d3b-bc68-b4d1552e04d1?apiKey=f40b658cd7ce4263a246966552f667ce&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/3c52da02-eb18-4d3b-bc68-b4d1552e04d1?apiKey=f40b658cd7ce4263a246966552f667ce&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/3c52da02-eb18-4d3b-bc68-b4d1552e04d1?apiKey=f40b658cd7ce4263a246966552f667ce&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/3c52da02-eb18-4d3b-bc68-b4d1552e04d1?apiKey=f40b658cd7ce4263a246966552f667ce&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/3c52da02-eb18-4d3b-bc68-b4d1552e04d1?apiKey=f40b658cd7ce4263a246966552f667ce&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/3c52da02-eb18-4d3b-bc68-b4d1552e04d1?apiKey=f40b658cd7ce4263a246966552f667ce&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/3c52da02-eb18-4d3b-bc68-b4d1552e04d1?apiKey=f40b658cd7ce4263a246966552f667ce&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/3c52da02-eb18-4d3b-bc68-b4d1552e04d1?apiKey=f40b658cd7ce4263a246966552f667ce&"
          className="absolute z-[-1] h-full w-full object-cover object-center inset-0"
        />
        <div className="relative flex w-full max-w-[1498px] flex-col items-stretch mt-12 mb-24 max-md:max-w-full max-md:my-10">
          <div className="text-white text-5xl font-extrabold leading-10 whitespace-nowrap max-md:max-w-full max-md:text-4xl max-md:leading-10">
            O KIT COMPLETO
          </div>
          <div className="mt-28 max-md:max-w-full max-md:mt-10">
            <div className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
              <div className="flex flex-col items-stretch w-3/12 max-md:w-full max-md:ml-0">
                <div className="shadow-2xl backdrop-blur-[7px] bg-zinc-500 bg-opacity-30 flex grow flex-col items-stretch w-full mx-auto px-2.5 py-10 rounded-3xl max-md:mt-10">
                  <img
                    loading="lazy"
                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/ff8dbec2-7528-4199-895b-d1bd15f89501?apiKey=f40b658cd7ce4263a246966552f667ce&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/ff8dbec2-7528-4199-895b-d1bd15f89501?apiKey=f40b658cd7ce4263a246966552f667ce&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/ff8dbec2-7528-4199-895b-d1bd15f89501?apiKey=f40b658cd7ce4263a246966552f667ce&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/ff8dbec2-7528-4199-895b-d1bd15f89501?apiKey=f40b658cd7ce4263a246966552f667ce&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/ff8dbec2-7528-4199-895b-d1bd15f89501?apiKey=f40b658cd7ce4263a246966552f667ce&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/ff8dbec2-7528-4199-895b-d1bd15f89501?apiKey=f40b658cd7ce4263a246966552f667ce&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/ff8dbec2-7528-4199-895b-d1bd15f89501?apiKey=f40b658cd7ce4263a246966552f667ce&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/ff8dbec2-7528-4199-895b-d1bd15f89501?apiKey=f40b658cd7ce4263a246966552f667ce&"
                    className="aspect-[1.48] object-contain object-center w-full overflow-hidden"
                  />
                  <div className="text-white text-4xl font-extrabold leading-8 self-center whitespace-nowrap mt-14 max-md:mt-10">
                    PETISQUEIRA
                  </div>
                </div>
              </div>
              <div className="flex flex-col items-stretch w-3/12 ml-5 max-md:w-full max-md:ml-0">
                <div className="backdrop-blur-[7px] bg-zinc-500 bg-opacity-30 flex grow flex-col items-stretch w-full mx-auto pl-6 pr-7 pt-12 pb-7 rounded-3xl max-md:mt-10 max-md:px-5">
                  <img
                    loading="lazy"
                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/43c33d40-e0a7-4193-a03f-db360bcc5ddb?apiKey=f40b658cd7ce4263a246966552f667ce&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/43c33d40-e0a7-4193-a03f-db360bcc5ddb?apiKey=f40b658cd7ce4263a246966552f667ce&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/43c33d40-e0a7-4193-a03f-db360bcc5ddb?apiKey=f40b658cd7ce4263a246966552f667ce&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/43c33d40-e0a7-4193-a03f-db360bcc5ddb?apiKey=f40b658cd7ce4263a246966552f667ce&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/43c33d40-e0a7-4193-a03f-db360bcc5ddb?apiKey=f40b658cd7ce4263a246966552f667ce&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/43c33d40-e0a7-4193-a03f-db360bcc5ddb?apiKey=f40b658cd7ce4263a246966552f667ce&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/43c33d40-e0a7-4193-a03f-db360bcc5ddb?apiKey=f40b658cd7ce4263a246966552f667ce&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/43c33d40-e0a7-4193-a03f-db360bcc5ddb?apiKey=f40b658cd7ce4263a246966552f667ce&"
                    className="aspect-[1.44] object-contain object-center w-full overflow-hidden mt-3"
                  />
                  <div className="text-white text-center text-4xl font-extrabold leading-8 whitespace-nowrap mt-11 max-md:mt-10">
                    BARALHO
                    <br />
                    PERSONALIZADO
                  </div>
                </div>
              </div>
              <div className="flex flex-col items-stretch w-3/12 ml-5 max-md:w-full max-md:ml-0">
                <div className="backdrop-blur-[7px] bg-zinc-500 bg-opacity-30 flex w-full grow flex-col items-center mx-auto pl-10 pr-10 pt-11 pb-9 rounded-3xl max-md:mt-10 max-md:px-5">
                  <div className="flex w-[203px] max-w-full items-stretch gap-0">
                    <img
                      loading="lazy"
                      srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/0143f2a4-0566-4a1a-b70b-14650ebf3d92?apiKey=f40b658cd7ce4263a246966552f667ce&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/0143f2a4-0566-4a1a-b70b-14650ebf3d92?apiKey=f40b658cd7ce4263a246966552f667ce&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/0143f2a4-0566-4a1a-b70b-14650ebf3d92?apiKey=f40b658cd7ce4263a246966552f667ce&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/0143f2a4-0566-4a1a-b70b-14650ebf3d92?apiKey=f40b658cd7ce4263a246966552f667ce&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/0143f2a4-0566-4a1a-b70b-14650ebf3d92?apiKey=f40b658cd7ce4263a246966552f667ce&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/0143f2a4-0566-4a1a-b70b-14650ebf3d92?apiKey=f40b658cd7ce4263a246966552f667ce&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/0143f2a4-0566-4a1a-b70b-14650ebf3d92?apiKey=f40b658cd7ce4263a246966552f667ce&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/0143f2a4-0566-4a1a-b70b-14650ebf3d92?apiKey=f40b658cd7ce4263a246966552f667ce&"
                      className="aspect-[0.43] object-contain object-center w-full overflow-hidden shrink-0 flex-1"
                    />
                    <img
                      loading="lazy"
                      srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/6c94210e-29aa-4e07-8918-d9a4b321b49b?apiKey=f40b658cd7ce4263a246966552f667ce&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/6c94210e-29aa-4e07-8918-d9a4b321b49b?apiKey=f40b658cd7ce4263a246966552f667ce&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/6c94210e-29aa-4e07-8918-d9a4b321b49b?apiKey=f40b658cd7ce4263a246966552f667ce&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/6c94210e-29aa-4e07-8918-d9a4b321b49b?apiKey=f40b658cd7ce4263a246966552f667ce&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/6c94210e-29aa-4e07-8918-d9a4b321b49b?apiKey=f40b658cd7ce4263a246966552f667ce&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/6c94210e-29aa-4e07-8918-d9a4b321b49b?apiKey=f40b658cd7ce4263a246966552f667ce&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/6c94210e-29aa-4e07-8918-d9a4b321b49b?apiKey=f40b658cd7ce4263a246966552f667ce&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/6c94210e-29aa-4e07-8918-d9a4b321b49b?apiKey=f40b658cd7ce4263a246966552f667ce&"
                      className="aspect-[0.43] object-contain object-center w-full overflow-hidden shrink-0 flex-1"
                    />
                  </div>
                  <div className="text-white text-4xl font-extrabold leading-8 self-stretch whitespace-nowrap mt-11 max-md:mt-10">
                    4 COPOS 270ml
                  </div>
                </div>
              </div>
              <div className="flex flex-col items-stretch w-3/12 ml-5 max-md:w-full max-md:ml-0">
                <div className="backdrop-blur-[7px] bg-zinc-500 bg-opacity-30 flex grow flex-col items-stretch w-full mx-auto pl-9 pr-8 py-8 rounded-3xl max-md:mt-10 max-md:px-5">
                  <img
                    loading="lazy"
                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/9bf3285f-1109-4452-bd19-5f486316a1d9?apiKey=f40b658cd7ce4263a246966552f667ce&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/9bf3285f-1109-4452-bd19-5f486316a1d9?apiKey=f40b658cd7ce4263a246966552f667ce&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/9bf3285f-1109-4452-bd19-5f486316a1d9?apiKey=f40b658cd7ce4263a246966552f667ce&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/9bf3285f-1109-4452-bd19-5f486316a1d9?apiKey=f40b658cd7ce4263a246966552f667ce&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/9bf3285f-1109-4452-bd19-5f486316a1d9?apiKey=f40b658cd7ce4263a246966552f667ce&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/9bf3285f-1109-4452-bd19-5f486316a1d9?apiKey=f40b658cd7ce4263a246966552f667ce&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/9bf3285f-1109-4452-bd19-5f486316a1d9?apiKey=f40b658cd7ce4263a246966552f667ce&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/9bf3285f-1109-4452-bd19-5f486316a1d9?apiKey=f40b658cd7ce4263a246966552f667ce&"
                    className="aspect-[1.14] object-contain object-center w-full overflow-hidden"
                  />
                  <div className="text-white text-center text-4xl font-extrabold leading-8 self-center whitespace-nowrap mt-8">
                    CONTADOR DE
                    <br />
                    PONTOS
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="self-center w-full max-w-[1650px] mt-2.5 max-md:max-w-full">
        <div className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
          <div className="flex flex-col items-stretch w-[47%] max-md:w-full max-md:ml-0">
            <div className="flex flex-col items-stretch my-auto px-5 max-md:max-w-full max-md:mt-10">
              <div className="text-white text-5xl font-extrabold leading-10 self-center whitespace-nowrap max-md:max-w-full max-md:text-4xl max-md:leading-10">
                DIVERSÃO COMPLETA
              </div>
              <div className="text-white text-center text-2xl font-extrabold leading-6 -mr-5 mt-12 max-md:max-w-full max-md:mt-10">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, <br />
                sed do eiusmod tempor incididunt ut labore et dolore magna
                aliqua. <br />
                Ut enim ad minim veniam, quis nostrud exercitation ullamco
                laboris <br />
                nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
                in <br />
                reprehenderit in voluptate velit esse cillum dolore eu fugiat
                nulla <br />
                pariatur. Excepteur sint occaecat cupidatat non proident, <br />
                sunt in culpa qui officia deserunt mollit anim id est laborum.
              </div>
              <div className="self-center w-[424px] max-w-full mt-16 max-md:mt-10">
                <div className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
                  <div className="flex flex-col items-stretch w-6/12 max-md:w-full max-md:ml-0">
                    <img
                      loading="lazy"
                      srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/e0ba19e1-34e0-460d-9717-be6c80e41fbf?apiKey=f40b658cd7ce4263a246966552f667ce&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/e0ba19e1-34e0-460d-9717-be6c80e41fbf?apiKey=f40b658cd7ce4263a246966552f667ce&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/e0ba19e1-34e0-460d-9717-be6c80e41fbf?apiKey=f40b658cd7ce4263a246966552f667ce&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/e0ba19e1-34e0-460d-9717-be6c80e41fbf?apiKey=f40b658cd7ce4263a246966552f667ce&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/e0ba19e1-34e0-460d-9717-be6c80e41fbf?apiKey=f40b658cd7ce4263a246966552f667ce&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/e0ba19e1-34e0-460d-9717-be6c80e41fbf?apiKey=f40b658cd7ce4263a246966552f667ce&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/e0ba19e1-34e0-460d-9717-be6c80e41fbf?apiKey=f40b658cd7ce4263a246966552f667ce&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/e0ba19e1-34e0-460d-9717-be6c80e41fbf?apiKey=f40b658cd7ce4263a246966552f667ce&"
                      className="aspect-[1.43] object-contain object-center w-[200px] backdrop-blur-[7px] overflow-hidden shrink-0 max-w-full grow max-md:mt-6"
                    />
                  </div>
                  <div className="flex flex-col items-stretch w-6/12 ml-5 max-md:w-full max-md:ml-0">
                    <img
                      loading="lazy"
                      srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/53dd5b09-e15a-4afb-a3ae-d113d36662cf?apiKey=f40b658cd7ce4263a246966552f667ce&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/53dd5b09-e15a-4afb-a3ae-d113d36662cf?apiKey=f40b658cd7ce4263a246966552f667ce&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/53dd5b09-e15a-4afb-a3ae-d113d36662cf?apiKey=f40b658cd7ce4263a246966552f667ce&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/53dd5b09-e15a-4afb-a3ae-d113d36662cf?apiKey=f40b658cd7ce4263a246966552f667ce&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/53dd5b09-e15a-4afb-a3ae-d113d36662cf?apiKey=f40b658cd7ce4263a246966552f667ce&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/53dd5b09-e15a-4afb-a3ae-d113d36662cf?apiKey=f40b658cd7ce4263a246966552f667ce&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/53dd5b09-e15a-4afb-a3ae-d113d36662cf?apiKey=f40b658cd7ce4263a246966552f667ce&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/53dd5b09-e15a-4afb-a3ae-d113d36662cf?apiKey=f40b658cd7ce4263a246966552f667ce&"
                      className="aspect-[1.43] object-contain object-center w-[200px] backdrop-blur-[7px] overflow-hidden shrink-0 max-w-full grow max-md:mt-6"
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="flex flex-col items-stretch w-[53%] ml-5 max-md:w-full max-md:ml-0">
            <img
              loading="lazy"
              srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/ccc9558e-e01a-40e4-a8e7-36974207bb11?apiKey=f40b658cd7ce4263a246966552f667ce&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/ccc9558e-e01a-40e4-a8e7-36974207bb11?apiKey=f40b658cd7ce4263a246966552f667ce&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/ccc9558e-e01a-40e4-a8e7-36974207bb11?apiKey=f40b658cd7ce4263a246966552f667ce&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/ccc9558e-e01a-40e4-a8e7-36974207bb11?apiKey=f40b658cd7ce4263a246966552f667ce&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/ccc9558e-e01a-40e4-a8e7-36974207bb11?apiKey=f40b658cd7ce4263a246966552f667ce&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/ccc9558e-e01a-40e4-a8e7-36974207bb11?apiKey=f40b658cd7ce4263a246966552f667ce&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/ccc9558e-e01a-40e4-a8e7-36974207bb11?apiKey=f40b658cd7ce4263a246966552f667ce&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/ccc9558e-e01a-40e4-a8e7-36974207bb11?apiKey=f40b658cd7ce4263a246966552f667ce&"
              className="aspect-[1.15] object-contain object-center w-full shadow-2xl overflow-hidden grow max-md:max-w-full max-md:mt-10"
            />
          </div>
        </div>
      </div>
      <div className="bg-emerald-800 self-stretch flex min-h-[4px] w-full flex-col max-md:max-w-full" />
      <div className="self-stretch w-full max-md:max-w-full">
        <div className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
          <div className="flex flex-col items-stretch w-[47%] max-md:w-full max-md:ml-0">
            <img
              loading="lazy"
              srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/d0cda75c-edca-48f3-ac42-e563b51e0e29?apiKey=f40b658cd7ce4263a246966552f667ce&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/d0cda75c-edca-48f3-ac42-e563b51e0e29?apiKey=f40b658cd7ce4263a246966552f667ce&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/d0cda75c-edca-48f3-ac42-e563b51e0e29?apiKey=f40b658cd7ce4263a246966552f667ce&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/d0cda75c-edca-48f3-ac42-e563b51e0e29?apiKey=f40b658cd7ce4263a246966552f667ce&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/d0cda75c-edca-48f3-ac42-e563b51e0e29?apiKey=f40b658cd7ce4263a246966552f667ce&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/d0cda75c-edca-48f3-ac42-e563b51e0e29?apiKey=f40b658cd7ce4263a246966552f667ce&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/d0cda75c-edca-48f3-ac42-e563b51e0e29?apiKey=f40b658cd7ce4263a246966552f667ce&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/d0cda75c-edca-48f3-ac42-e563b51e0e29?apiKey=f40b658cd7ce4263a246966552f667ce&"
              className="aspect-[1.15] object-contain object-center w-full overflow-hidden grow max-md:max-w-full"
            />
          </div>
          <div className="flex flex-col items-stretch w-[53%] ml-5 max-md:w-full max-md:ml-0">
            <div className="flex flex-col mt-16 px-5 max-md:max-w-full max-md:mt-10">
              <div className="text-white text-5xl font-extrabold leading-10 self-center whitespace-nowrap ml-14 max-md:text-4xl max-md:leading-10">
                AVALIAÇÕES
              </div>
              <div className="self-stretch flex justify-between gap-5 -mr-5 mt-11 max-md:max-w-full max-md:flex-wrap max-md:mt-10">
                <img
                  loading="lazy"
                  srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/bb70006e-0da0-4fb5-9756-bcd07a86498c?apiKey=f40b658cd7ce4263a246966552f667ce&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/bb70006e-0da0-4fb5-9756-bcd07a86498c?apiKey=f40b658cd7ce4263a246966552f667ce&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/bb70006e-0da0-4fb5-9756-bcd07a86498c?apiKey=f40b658cd7ce4263a246966552f667ce&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/bb70006e-0da0-4fb5-9756-bcd07a86498c?apiKey=f40b658cd7ce4263a246966552f667ce&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/bb70006e-0da0-4fb5-9756-bcd07a86498c?apiKey=f40b658cd7ce4263a246966552f667ce&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/bb70006e-0da0-4fb5-9756-bcd07a86498c?apiKey=f40b658cd7ce4263a246966552f667ce&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/bb70006e-0da0-4fb5-9756-bcd07a86498c?apiKey=f40b658cd7ce4263a246966552f667ce&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/bb70006e-0da0-4fb5-9756-bcd07a86498c?apiKey=f40b658cd7ce4263a246966552f667ce&"
                  className="aspect-square object-contain object-center w-[90px] overflow-hidden shrink-0 max-w-full mt-3.5 rounded-[50%]"
                />
                <div className="self-stretch flex grow basis-[0%] flex-col max-md:max-w-full">
                  <div className="text-white text-xl leading-6 whitespace-nowrap ml-3 max-md:ml-2.5">
                    André Alves
                  </div>
                  <div className="text-white text-xl leading-6 w-[650px] max-w-full backdrop-blur-[7px] bg-zinc-500 bg-opacity-30 self-stretch mt-1.5 px-3.5 py-6 rounded-3xl max-md:max-w-full">
                    “Kit truco fascinante, ideal para jogar com amigos ou dar de
                    presente.”
                  </div>
                </div>
              </div>
              <div className="self-stretch flex justify-between gap-5 -mr-5 mt-16 max-md:max-w-full max-md:flex-wrap max-md:mt-10">
                <img
                  loading="lazy"
                  srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/db207017-7b23-4533-b541-c045879c18e9?apiKey=f40b658cd7ce4263a246966552f667ce&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/db207017-7b23-4533-b541-c045879c18e9?apiKey=f40b658cd7ce4263a246966552f667ce&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/db207017-7b23-4533-b541-c045879c18e9?apiKey=f40b658cd7ce4263a246966552f667ce&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/db207017-7b23-4533-b541-c045879c18e9?apiKey=f40b658cd7ce4263a246966552f667ce&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/db207017-7b23-4533-b541-c045879c18e9?apiKey=f40b658cd7ce4263a246966552f667ce&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/db207017-7b23-4533-b541-c045879c18e9?apiKey=f40b658cd7ce4263a246966552f667ce&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/db207017-7b23-4533-b541-c045879c18e9?apiKey=f40b658cd7ce4263a246966552f667ce&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/db207017-7b23-4533-b541-c045879c18e9?apiKey=f40b658cd7ce4263a246966552f667ce&"
                  className="aspect-square object-contain object-center w-[90px] overflow-hidden shrink-0 max-w-full mt-3 rounded-[50%]"
                />
                <div className="self-stretch flex grow basis-[0%] flex-col max-md:max-w-full">
                  <div className="text-white text-xl leading-6 whitespace-nowrap ml-3 max-md:ml-2.5">
                    Roberta Gonçalves
                  </div>
                  <div className="text-white text-xl leading-6 w-[650px] max-w-full backdrop-blur-[7px] bg-zinc-500 bg-opacity-30 self-stretch px-3.5 py-6 rounded-3xl max-md:max-w-full">
                    “Produto muito bom ! Chegou antes do prazo e veio tudo bem
                    embalado.”
                  </div>
                </div>
              </div>
              <div className="self-stretch flex justify-between gap-5 -mr-5 mt-16 max-md:max-w-full max-md:flex-wrap max-md:mt-10">
                <img
                  loading="lazy"
                  srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/76030770-eb68-4943-8cd4-0726dd3ab5a9?apiKey=f40b658cd7ce4263a246966552f667ce&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/76030770-eb68-4943-8cd4-0726dd3ab5a9?apiKey=f40b658cd7ce4263a246966552f667ce&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/76030770-eb68-4943-8cd4-0726dd3ab5a9?apiKey=f40b658cd7ce4263a246966552f667ce&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/76030770-eb68-4943-8cd4-0726dd3ab5a9?apiKey=f40b658cd7ce4263a246966552f667ce&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/76030770-eb68-4943-8cd4-0726dd3ab5a9?apiKey=f40b658cd7ce4263a246966552f667ce&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/76030770-eb68-4943-8cd4-0726dd3ab5a9?apiKey=f40b658cd7ce4263a246966552f667ce&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/76030770-eb68-4943-8cd4-0726dd3ab5a9?apiKey=f40b658cd7ce4263a246966552f667ce&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/76030770-eb68-4943-8cd4-0726dd3ab5a9?apiKey=f40b658cd7ce4263a246966552f667ce&"
                  className="aspect-square object-contain object-center w-[90px] overflow-hidden shrink-0 max-w-full mt-3 rounded-[50%]"
                />
                <div className="self-stretch flex grow basis-[0%] flex-col max-md:max-w-full">
                  <div className="text-white text-xl leading-6 whitespace-nowrap ml-3 max-md:ml-2.5">
                    Juliano Pereira
                  </div>
                  <div className="text-white text-xl leading-6 w-[650px] max-w-full backdrop-blur-[7px] bg-zinc-500 bg-opacity-30 self-stretch mt-1.5 px-3.5 py-6 rounded-3xl max-md:max-w-full">
                    “Kit truco fascinante, ideal para jogar com amigos ou dar de
                    presente”
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="self-center w-full max-w-[1664px] max-md:max-w-full">
        <div className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
          <div className="flex flex-col items-stretch w-[48%] max-md:w-full max-md:ml-0">
            <div className="flex flex-col items-stretch my-auto px-5 max-md:max-w-full max-md:mt-10">
              <div className="text-white text-5xl font-extrabold leading-10 whitespace-nowrap -mr-5 max-md:max-w-full max-md:text-4xl max-md:leading-10">
                COMPRE AGORA
              </div>
              <div className="text-white text-2xl font-extrabold leading-6 whitespace-nowrap -mr-5 max-md:max-w-full">
                ENVIO IMEDIATO
              </div>
              <div className="text-white text-2xl leading-6 whitespace-nowrap -mr-5 mt-16 max-md:max-w-full max-md:mt-10">
                ESCOLHA A QUANTIDADE:
              </div>
              <div className="-mr-5 mt-10 max-md:max-w-full max-md:mt-10">
                <div className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
                  <div className="flex flex-col items-stretch w-[33%] max-md:w-full max-md:ml-0">
                    <div className="backdrop-blur-[7px] bg-zinc-500 bg-opacity-30 flex grow flex-col items-stretch w-full mx-auto px-16 py-12 rounded-3xl max-md:mt-6 max-md:px-5">
                      <div className="text-white text-2xl font-extrabold leading-6 whitespace-nowrap">
                        6 KITS
                      </div>
                      <div className="text-neutral-400 text-xl font-extrabold leading-5 whitespace-nowrap mt-4">
                        50% OFF
                      </div>
                    </div>
                  </div>
                  <div className="flex flex-col items-stretch w-[33%] ml-5 max-md:w-full max-md:ml-0">
                    <div className="backdrop-blur-[7px] bg-zinc-500 bg-opacity-30 flex grow flex-col items-stretch w-full mx-auto px-16 py-12 rounded-3xl max-md:mt-6 max-md:px-5">
                      <div className="text-white text-2xl font-extrabold leading-6 whitespace-nowrap">
                        3 KITS
                      </div>
                      <div className="text-neutral-400 text-xl font-extrabold leading-5 whitespace-nowrap mt-4">
                        50% OFF
                      </div>
                    </div>
                  </div>
                  <div className="flex flex-col items-stretch w-[33%] ml-5 max-md:w-full max-md:ml-0">
                    <div className="backdrop-blur-[7px] bg-zinc-500 bg-opacity-30 flex grow flex-col items-center w-full mx-auto px-16 py-12 rounded-3xl max-md:mt-6 max-md:px-5">
                      <div className="text-white text-2xl font-extrabold leading-6 whitespace-nowrap">
                        1 KIT
                      </div>
                      <div className="text-neutral-400 text-xl font-extrabold leading-5 self-stretch whitespace-nowrap mt-4">
                        50% OFF
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="flex items-stretch justify-between gap-4 -mr-5 mt-10 max-md:max-w-full max-md:flex-wrap max-md:justify-center">
                <div className="text-white text-xl font-extrabold leading-5 whitespace-nowrap grow items-stretch px-5 py-6 max-md:pr-0">
                  ADICIONAR AO CARRINHO
                </div>
                <div className="text-white text-2xl font-extrabold leading-6 blur-[2px] my-auto">
                  R$100,00
                </div>
                <div className="text-white text-2xl font-extrabold leading-6 self-center whitespace-nowrap my-auto">
                  R$40,00
                </div>
              </div>
            </div>
          </div>
          <div className="flex flex-col items-stretch w-[52%] ml-5 max-md:w-full max-md:ml-0">
            <img
              loading="lazy"
              srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/d4ba5f4c-1fac-4ddd-a1aa-33f38f06c87a?apiKey=f40b658cd7ce4263a246966552f667ce&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/d4ba5f4c-1fac-4ddd-a1aa-33f38f06c87a?apiKey=f40b658cd7ce4263a246966552f667ce&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/d4ba5f4c-1fac-4ddd-a1aa-33f38f06c87a?apiKey=f40b658cd7ce4263a246966552f667ce&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/d4ba5f4c-1fac-4ddd-a1aa-33f38f06c87a?apiKey=f40b658cd7ce4263a246966552f667ce&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/d4ba5f4c-1fac-4ddd-a1aa-33f38f06c87a?apiKey=f40b658cd7ce4263a246966552f667ce&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/d4ba5f4c-1fac-4ddd-a1aa-33f38f06c87a?apiKey=f40b658cd7ce4263a246966552f667ce&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/d4ba5f4c-1fac-4ddd-a1aa-33f38f06c87a?apiKey=f40b658cd7ce4263a246966552f667ce&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/d4ba5f4c-1fac-4ddd-a1aa-33f38f06c87a?apiKey=f40b658cd7ce4263a246966552f667ce&"
              className="aspect-[1.2] object-contain object-center w-full shadow-sm overflow-hidden grow max-md:max-w-full max-md:mt-10"
            />
          </div>
        </div>
      </div>
      <div className="bg-emerald-800 self-stretch flex min-h-[4px] w-full flex-col max-md:max-w-full" />
      <div className="bg-black self-stretch flex w-full flex-col items-stretch pt-12 max-md:max-w-full">
        <div className="bg-emerald-800 flex min-h-[4px] w-full flex-col mt-64 max-md:max-w-full max-md:mt-10" />
      </div>
    </div>
  );
}