/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

function UpdatedComponent(props) {
  return (
    <main className="bg-sky-950 flex flex-col items-center">
      <section className="flex w-full max-w-[982px] flex-col items-stretch mt-7 max-md:max-w-full">
        <div className="max-md:max-w-full">
          <div className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
            <div className="flex flex-col items-stretch w-[24%] max-md:w-full max-md:ml-0">
              <div className="bg-blue-600 flex w-36 shrink-0 h-[7px] flex-col mt-48 mx-auto rounded-[100px] max-md:mt-10" />
            </div>
            <div className="flex flex-col items-stretch w-[76%] ml-5 max-md:w-full max-md:ml-0">
              <div className="flex grow flex-col max-md:max-w-full max-md:mt-10">
                <img
                  loading="lazy"
                  srcSet="..."
                  className="aspect-square object-contain object-center w-[150px] overflow-hidden max-w-full"
                />
                <div className="bg-blue-600 flex w-36 shrink-0 h-[7px] flex-col mt-11 rounded-[100px] self-end max-md:mt-10" />
              </div>
            </div>
          </div>
        </div>
        <div className="bg-blue-600 self-center flex ml-0 w-36 shrink-0 h-[7px] flex-col mt-5 rounded-[100px]" />
      </section>
      <section className="self-stretch flex w-full flex-col items-stretch mt-4 pl-20 pr-14 max-md:max-w-full max-md:px-5">
        <div className="flex justify-between gap-1 max-md:max-w-full max-md:flex-wrap">
          <div className="bg-blue-600 flex w-36 shrink-0 h-[7px] flex-col mt-4 rounded-[100px]" />
          <h1 className="text-white text-center text-3xl font-extrabold self-stretch whitespace-nowrap max-md:max-w-full">
            TENHA LIBERDADE DE TRABALHAR ONDE E QUANDO QUISER !
          </h1>
        </div>
        <div className="flex w-[946px] max-w-full justify-between gap-5 mt-9 self-end max-md:flex-wrap">
          <div className="bg-blue-600 flex shrink-0 h-[7px] flex-col flex-1 rounded-[100px]" />
          <div className="bg-blue-600 flex shrink-0 h-[7px] flex-col flex-1 rounded-[100px]" />
        </div>
      </section>
      <section className="self-stretch flex w-full flex-col mt-5 mb-24 px-14 max-md:max-w-full max-md:mb-10 max-md:px-5">
        <div className="self-stretch flex items-center justify-between gap-0 max-md:max-w-full max-md:flex-wrap max-md:justify-center">
          <div className="flex basis-[0%] flex-col items-stretch -mr-16 my-auto">
            <div className="flex justify-between gap-0">
              <div className="bg-blue-600 flex w-36 shrink-0 h-[7px] flex-col mt-28 rounded-[100px] max-md:mt-10" />
              <div className="self-stretch flex grow basis-[0%] flex-col items-stretch pb-28 max-md:pb-24">
                <img
                  loading="lazy"
                  srcSet="..."
                  className="aspect-[1.45] object-contain object-center w-[174px] overflow-hidden z-[1]"
                />
                <div className="bg-blue-600 flex mt-0 w-36 shrink-0 h-[7px] flex-col mb-24 rounded-[100px] self-end max-md:mb-10" />
              </div>
            </div>
            <div className="bg-blue-600 self-center flex w-36 shrink-0 h-[7px] flex-col mt-32 rounded-[100px] max-md:mt-10" />
            <div className="bg-blue-600 flex shrink-0 h-[7px] flex-col mt-28 rounded-[100px] max-md:mt-10" />
            <div className="bg-blue-600 self-center flex w-36 shrink-0 h-[7px] flex-col mt-28 rounded-[100px] max-md:mt-10" />
          </div>
          <div className="flex-col overflow-hidden self-stretch relative z-[1] flex min-h-[563px] grow basis-[0%] pt-[510px] pb-12 px-5 max-md:max-w-full max-md:mr-0 max-md:pt-24">
            <img
              loading="lazy"
              srcSet="..."
              className="absolute z-[-1] h-full w-full object-cover object-center inset-0"
            />
            <div className="relative bg-blue-600 flex w-36 shrink-0 h-[7px] flex-col mr-36 rounded-[100px] max-md:mr-2.5" />
          </div>
          <div className="flex basis-[0%] flex-col items-stretch mt-56 self-start max-md:mt-10">
            <div className="bg-blue-600 flex shrink-0 h-[7px] flex-col rounded-[100px]" />
            <div className="bg-blue-600 flex shrink-0 h-[7px] flex-col mt-52 rounded-[100px] max-md:mt-10" />
          </div>
        </div>
      </section>
      <section className="text-white text-center text-3xl font-extrabold max-w-[1046px] self-center mt-20 max-md:max-w-full max-md:mt-10">
        APRENDA EM POUCO TEMPO E COMECE A RECEBER ALTAS OFERTAS
        <br />
        FAZENDO O QUE GOSTA.
      </section>
      <section className="bg-slate-900 self-center flex w-[1024px] shrink-0 h-[417px] flex-col mt-24 rounded-3xl max-md:max-w-full max-md:mt-10" />
      <section className="text-white text-center text-3xl font-extrabold self-center max-w-[422px] mt-32 max-md:mt-10">
        INSCREVA-SE
      </section>
      <section className="text-white text-lg ml-80 mt-11 max-md:ml-2.5 max-md:mt-10">NOME</section>
      <input
        type="text"
        className="bg-white self-center flex w-[646px] shrink-0 h-[38px] flex-col mt-1.5 max-md:max-w-full"
      />
      <section className="text-white text-lg ml-80 mt-4 max-md:ml-2.5">EMAIL</section>
      <input
        type="email"
        className="bg-white self-center flex w-[646px] shrink-0 h-[38px] flex-col mt-1.5 max-md:max-w-full"
      />
      <section className="text-white text-center text-3xl font-extrabold max-w-full self-center w-[452px] items-center mt-14 px-5 py-5 max-md:mt-10">
        RECEBER MATERIAL
      </section>
    </main>
  );
}